"""Increase password length to 500

Revision ID: 22161e9a3de0
Revises: 33829dc6cd9c
Create Date: 2024-11-17 11:44:54.117857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22161e9a3de0'
down_revision = '33829dc6cd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
